### ISSUE TITLE
Run beforeScript Functions in task

### ISSUE THREAD

**Issue by una** [pa11y/webservice#42] opened 2016-11-14 16:31 UTC
In order to get past a login form, beforeScript tasks are [required](https://github.com/pa11y/pa11y#how-can-pa11y-log-in-if-my-site-has-a-log-in-form). This works great with JS wrappers over pa11y but does not work when combined with the webservice (which is the basis for pa11y dashboard, so login with a separate screen also doesn't work through there). 

I was hoping to make this possible, or maybe I'm just missing something?

**Comment by hollsk** [comment] 2016-11-15 19:03
hey @una - unfortunately we don't yet expose that feature to the webservice/dashboard. You're not the first person to have asked us this, so we should really look at making this possible. I'll leave this issue open and discuss it with the team. 

It is possible to log in with the webservice using HTTP basic authentication, if that helps you at all in the meantime. Here's the endpoint reference: https://github.com/pa11y/webservice/wiki/Web-Service-Endpoints

From the Dashboard, it's a case of adding the basic auth username/password when you set up a URL.

**Comment by una** [comment] 2016-11-17 19:59
@hollsk I'm wondering what it would take to add a beforeScript option as a possibility in the webservice? Currently, I'm forced to set up my own web service using pa11y as a JavaScript wrapper because I need to run a beforeScript hook.

Would love to help in any way I can

**Comment by rowanmanning** [comment] 2016-11-18 11:36
Jumping in quickly to say that it shouldn't be _too_ much work to add a beforeScript option, but would need to ensure that it's not possible to take down the webservice with beforeScript JavaScript.

I'm not sure what your setup is like, @una, but we did recently add the ability to send custom headers in the dashboard/webservice. A possible alternate solution would be to send a cookie for a logged in user.

**Comment by una** [comment] 2016-11-18 17:28
Thanks @rowanmanning -- I just looked into it and it doesn't look like I'll be able to use cookies for my use case.

(plus a beforeScript would add a lot more customization opportunity!) 😄

**Comment by rowanmanning** [comment] 2016-11-22 09:33
Cool, in that case adding beforeScript should be do-able. The first step would be adding it to the webservice.

I guess we'd need to store the full script as a string, possibly without the wrapping function – we'll probably have to use `eval` or [Node.js sandbox](https://github.com/gf3/sandbox) to actually execute the script which means that when it saves we should probably ensure that it's valid JS.

Adding a regular text field is relatively straightforward, #24 is a good example of a field being added. We'll need a bit more work for beforeScript because running user-input JS is a bit of a minefield and we don't want it to be possible to crash the app with it.

After we've got a webservice PR in place we can look at how we expose it in dashboard, e.g would we want a code editor/syntax highlighting?

**Comment by rowanmanning** [comment] 2017-03-27 10:55
I'm going to close this as we've added actions to the webservice, and after some investigation it'd be really difficult to enable beforeScript securely.

**Closed by rowanmanning** 2017-03-27 10:55 UTC
Labels: type: enhancement

**Comment by mayankagarwal8188** [comment] 2018-02-14 10:56
Hi,

I am trying to add the beforescript function in pa11y beta version - 5.0.0-beta.8. But it seems to be not working for me. any suggestions?

please find below my code :- 

// An example of injecting a script before Pa11y runs.
// This example logs in to a fictional site then waits
// until the account page has loaded before running Pa11y
'use strict';


var pa11y = require('pa11y');

// Create a test instance with some default options
pa11y('http://mypage.com/',{
	// Log what's happening to the console
	timeout: 9000000,
	chromeLaunchConfig: {
        executablePath: 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',
        ignoreHTTPSErrors: false,
		headless:false
    },
	log: {
		debug: console.log.bind(console),
		error: console.error.bind(console),
		info: console.log.bind(console)
	},

	// A script to be run on the inital page before Pa11y is run.
	// beforeScript accepts three parameters, the page object, the pa11y options and a callback
	beforeScript: function(page, options, next) {

		options.log.debug(' >>> beforeScript called ');
		// An example function that can be used to make sure changes have been confirmed before continuing to run Pa11y
		var waitUntil = function(condition, retries, waitOver) {
			page.evaluate(condition, function(error, result) {
				if (result || retries < 1) {
					// Once the changes have taken place continue with Pa11y testing
					waitOver();
				} else {
					retries -= 1;
					setTimeout(function() {
						waitUntil(condition, retries, waitOver);
					}, 200);
				}
			});
		};

		// The script to manipulate the page must be run with page.evaluate to be run within the context of the page
		page.evaluate(function() {
			window.location.href = 'mypage.com/';
			console.log("1111");
		},function(){

			// Use the waitUntil function to set the condition, number of retries and the callback
			waitUntil(function() {
				return window.location.href === 'mypage.com/';
			}, 20, function() {
              // log in
              var user = document.querySelector('.log-in');
              var password = document.querySelector('login-details');
              //var submit = document.querySelector('#submit');

              //user.value = 'exampleUser';
              //password.value = 'password1234';

              user.click();
            }, function() {
              waitUntil(function() {
                // wait for the page to load on the page we want to test
                return password ? true : false;
			  }, 20, next);
			})
		});

	}
}).then(result => {
	console.log(result);
})
.catch(error => {
	console.error(error.message);
});

**Comment by rowanmanning** [comment] 2018-02-14 12:25
Hi @mayankagarwal8188. This isn't the right place for this query, as it relates to Pa11y. In future could you open a [new issue here](https://github.com/pa11y/pa11y/issues) for Pa11y CLI issues?

And yes, Pa11y 5.x removes support for `beforeScript`. There my be a new way to hook into the page before running, but we're removing in favour of actions. This is [mentioned in the migration guide here](https://github.com/pa11y/pa11y/blob/5.x/MIGRATION.md#configuration).

I've opened this issue to provide an example of how to achieve similar in Pa11y 5.x https://github.com/pa11y/pa11y/issues/383
